# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: "*/30 12 * * *"
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - name: Build packages
      run: |
        pacman -Syu --needed --noconfirm --noprogressbar 
        pacman -S --needed --noconfirm sudo midori fakeroot git lxdm-gtk3 arc-gtk-theme adapta-gtk-theme
        useradd -p builderbob -c builderbob -m builderbob
        echo "builderbob:builderbob"|chpasswd
        tee -a /etc/sudoers > /dev/null <<EOT
        builderbob    ALL=(ALL) NOPASSWD:ALL
        EOT
        git clone https://github.com/Aeolus-Linux/aeolus-pkgs/
        tee -a /etc/pacman.conf > /dev/null <<EOT
        [aeolus-pkgs]
        SigLevel = Optional TrustAll
        Server = https://aeolus-linux.github.io/aeolus-pkgs/$arch
        EOT
        sudo pacman -Syyu
        cd aeolus-pkgs
        chmod -777 *
        git init
        git add *
        pacman -Syyu --noconfirm
        chmod +x build.sh
        pwd
        #su -c "./build.sh" builderbob
        mkdir goo
        cd goo
        cp /etc/pacman.conf ./
        mv pacman.conf goo
        echo $GITHUB_REPOSITORY
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <Update Packages>
          skip-checks: true
      run: |
        # Hard-code user configuration
        git config user.email "tysayahi@gmail.com"
        git config user.name "Eile Kerning"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
