# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build packages
      run: |
        pacman -Syu --needed --noconfirm --noprogressbar 
        pacman -S --needed --noconfirm sudo 
        useradd -p builderbob -c builderbob -m builderbob
        echo "builderbob:builderbob"|chpasswd
        tee -a /etc/sudoers > /dev/null <<EOT
        builderbob    ALL=(ALL) NOPASSWD:ALL
        EOT
        pacman -Syu --noconfirm
        pwd
        pacman -Sy --needed --noconfirm coreutils kmod linux-firmware bc git graphviz imagemagick kmod git fakeroot libelf pahole python-spinx_rtd_theme xmlto crda autogen cmake 
        pacman -Sy --needed --noconfirm python-sphinx grub git meson perl fish tmux libglade python2-cairo python2-gobject2 python2-numpy  vim zsh git go i3-wm python2 python pacman-contrib expac fzf libpulse 
        pacman -Sy --needed --noconfirm libmpdclient perl-data-dump perl sudo fakeroot gtk2-perl perl-file-desktopentry perl-gtk3 efibootmgr base-devel python rsync fuse2 xorg-xauth libxinerama gtk3 libxrandr libxcursor 
        pacman -Sy --needed --noconfirm imlib2 libqalculate hicolor-icon-theme gtk-update-icon-cache git sudo fakeroot go binutils rofi  docbook-xsl libdrm patch autoconf automake gcc bdf-unifont help2man ttf-dejavu
        pwd
        chmod +x build.sh
        pwd
        su -c "./build.sh" builderbob
        
    - name: Upload repo
      uses: actions/upload-artifact@v2.1.4
      with:
        name: aeolus-pkgs
        path: ./
        if-no-files-found: error

