# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: "*/30 12 * * *"
    - cron: "*/30 23 * * *"
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - name: Build packages
      run: |
        pacman -Syu --needed --noconfirm --noprogressbar 
        pacman -Syyu --needed --noconfirm sudo git --noprogressbar
        pacman -S --needed --noconfirm base-devel binutils sudo midori fakeroot git lxdm-gtk3 arc-gtk-theme adapta-gtk-theme
        useradd -p builderbob -c builderbob -m builderbob
        echo "builderbob:builderbob"|chpasswd
        tee -a /etc/sudoers > /dev/null <<EOT
        builderbob    ALL=(ALL) NOPASSWD:ALL
        EOT
        git clone https://github.com/Osmium-Linux/osmium-pkgs.git
        chmod -R 777 ./osmium-pkgs/
        chown -R builderbob:builderbob ./osmium-pkgs/
        cd osmium-pkgs
        rm -rf aur_pkgs
        mkdir aur_pkgs
        rm -rf yay
        rm -rf pygtk
        rm -rf ./x86_64/*
        mkdir x86_64
        git clone https://github.com/Osmium-Linux/linux-tkg-noninteractive.git
        cp ./linux-tkg-noninteractive/output/*.pkg.tar.zst ./x86_64/
        rm -rf linux-tkg-noninteractive
        cd ./osmium-pkgs/
        dir
        ls
        pwd
        pacman -Syyu --noconfirm
        chmod 777 build.sh
        chmod +x build.sh
        chown builderbob:builderbob build.sh 
        pwd
        cd x86_64 
        pwd
        DBDIR="$(pwd)"
        printf 'y\n' | sudo pacman -Scc
        sudo pacman -Syyu
        cd ..
        ls -l build.sh
        git init
        git add *
        su -c "sh build.sh" builderbob
        rm -rf aur_pkgs
        mkdir aur_pkgs
        rm -rf yay
        rm -rf pygtk
        cd ./x86_64/
        git add *
        cd ..
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <Update Packages>
          skip-checks: true
      run: |
        # Hard-code user configuration
        pwd
        cd osmium-pkgs
        git config user.email "tysayahi@gmail.com"
        git config user.name "Eile Kerning"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
