# This is a basic workflow to help you get started with Actions

name: Cleanup

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: '01 01 * * 00'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clean:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - name: Clean Repo
      run: |
        git clone --depth 1 https://github.com/Osmium-Linux/osmium-pkgs.git
        chmod -R 777 ./osmium-pkgs/
        cd osmium-pkgs
        rm -rf ./x86_64/
        mkdir -p ./x86_64/
        git clone https://github.com/Osmium-Linux/linux-tkg-noninteractive.git
        cp ./linux-tkg-noninteractive/output/*.pkg.tar.zst ./x86_64/
        rm -rf linux-tkg-noninteractive
        git init
        git add *
        cd ./x86_64/
        git add *
        cd ..
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <Clean Repository>
          skip-checks: true
      run: |
        # Hard-code user configuration
        pwd
        cd osmium-pkgs
        git config user.email "tysayahi@gmail.com"
        git config user.name "Eile Kerning"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)

