# This is a basic workflow to help you get started with Actions

name: Cleanup

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: '01 01 * * 00'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Clean Repo
      run: |
        #!/bin/bash
        set -x #echo on
        sudo apt install git default-jre -y 
        java -version
        git clone --mirror https://github.com/Osmium-Linux/osmium-pkgs.git
        cd osmium-pkgs.git
        wget https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar
        java -jar bfg-*.jar --strip-blobs-bigger-than 1M 
        git reflog expire --expire=now --all && git gc --prune=now --aggressive
        rm bfg-*.jar
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <Clean Git History>
          skip-checks: true
      run: |
        # Hard-code user configuration
        #!/bin/bash
        set -x #echo on
        pwd
        cd osmium-pkgs.git
        echo 1
        git config user.email "tysayahi@gmail.com"
        echo 2
        git config user.name "Eile Kerning"
        echo 3
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        echo 4
        # Checkout the branch so we can push back to it
        echo 6 
        echo git add .
        echo 7
        git push origin master

