# This is a basic workflow to help you get started with Actions

name: Create pkg database

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: '20 03 * * 00'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  osmium-no-deps:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - name: Build database
      run: |
        #!/bin/bash -x
        useradd -p builderbob -c builderbob -m builderbob
        echo "builderbob:builderbob"|chpasswd
        tee -a /etc/sudoers > /dev/null <<EOT
        builderbob    ALL=(ALL) NOPASSWD:ALL
        EOT
        pacman -Sy git sudo --noconfirm
        git clone https://github.com/Osmium-Linux/osmium-pkgs.git
        cd ./osmium-pkgs/
        rm -rf ./x86_64/
        mkdir -p ./x86_64
        mv ./w86_64/* ./x86_64/
        cd ./x86_64
        repo-add -n osmium-pkgs.db.tar.gz *.pkg.tar.zst
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <Update Aur Pkgs>
          skip-checks: true
      run: |
        #!/bin/bash -x
        # Hard-code user configuration
        pwd
        cd osmium-pkgs
        git config user.email "tysayahi@gmail.com"
        git config user.name "Eile Kerning"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
