# This is a basic workflow to help you get started with Actions

name: Osmium-LXDM

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  schedule: 
    - cron: '20 01 * * 01'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  osmium-lxdm:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged

    steps:
    - name: Build packages
      run: |
        useradd -p builderbob -c builderbob -m builderbob
        echo "builderbob:builderbob"|chpasswd
        tee -a /etc/sudoers > /dev/null <<EOT
        builderbob    ALL=(ALL) NOPASSWD:ALL
        EOT
        #tee -a /etc/pacman.conf > /dev/null <<EOT
        #[osmium-pkgs]
        #SigLevel = Optional TrustAll
        #Server = https://osmium-linux.github.io/osmium-pkgs/x86_64
        #EOT
        useradd -p builderbob -c builderbob -m builderbob
        echo "builderbob:builderbob"|chpasswd
        tee -a /etc/sudoers > /dev/null <<EOT
        builderbob    ALL=(ALL) NOPASSWD:ALL
        EOT
        pacman -Sy --noconfirm git
        git clone https://github.com/Osmium-Linux/osmium-pkgs.git
        chmod -R 777 ./osmium-pkgs/
        chown -R builderbob:builderbob ./osmium-pkgs/
        cd osmium-pkgs
        rm -rf aur_pkgs
        mkdir aur_pkgs
        chmod 777 build.sh
        chmod +x build.sh
        chown builderbob:builderbob build.sh 
        cd x86_64 
        DBDIR="$(pwd)"
        printf 'y\n' | sudo pacman -Scc
        cd ..
        ls -l build.sh
        git init
        git add *
        su -c "sh build.sh" builderbob
        chmod +x lxdm-themes.sh
        su -c "sh lxdm-themes.sh" builderbob
        cd ./x86_64/
        git add *
        cd ..
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          <Update Osmium Custom LXDM Themes>
          skip-checks: true
      run: |
        # Hard-code user configuration
        pwd
        cd osmium-pkgs
        git config user.email "tysayahi@gmail.com"
        git config user.name "Eile Kerning"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
